name: Update NYT Puzzle Stats

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust time as needed)
    - cron: "0 9 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update NYT Stats
        env:
          NYT_COOKIE: ${{ secrets.NYT_COOKIE }}
        run: |
          python nyt_stats.py

      - name: Checkout profile repository
        uses: actions/checkout@v3
        with:
          repository: mpartificer/mpartificer
          path: profile-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create and run update script
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Set up the remote URL with authentication
          cd profile-repo
          git remote set-url origin https://x-access-token:$PERSONAL_ACCESS_TOKEN@github.com/mpartificer/mpartificer.git
          cd ..

          cat > update_profile.py << 'EOF'
          import re
          import os
          import subprocess

          def update_profile_readme():
              """Update profile README with NYT stats"""
              # Define paths
              source_readme = 'README.md'
              target_readme = 'profile-repo/README.md'
              
              # Define markers
              start_marker = "<!-- NYT_STATS_START -->"
              end_marker = "<!-- NYT_STATS_END -->"
              
              # Read source README (the one with fresh stats)
              with open(source_readme, 'r') as f:
                  source_content = f.read()
              
              # Extract stats content
              stats_pattern = re.compile(f"{start_marker}.*?{end_marker}", re.DOTALL)
              stats_match = stats_pattern.search(source_content)
              
              if not stats_match:
                  print("Could not find stats markers in source README")
                  return False
                  
              stats_content = stats_match.group(0)
              
              # Check if target README exists
              if not os.path.exists(target_readme):
                  print("Profile README doesn't exist, creating it")
                  with open(target_readme, 'w') as f:
                      f.write(f"# My GitHub Profile\n\n{stats_content}\n")
                  return True
              
              # Read target README (profile README)
              with open(target_readme, 'r') as f:
                  profile_content = f.read()
              
              # Update or append stats
              if start_marker in profile_content:
                  print("Updating existing stats in profile README")
                  updated_content = stats_pattern.sub(stats_content, profile_content)
              else:
                  print("Adding stats to profile README")
                  updated_content = f"{profile_content}\n\n{stats_content}\n"
              
              # Write updated content
              with open(target_readme, 'w') as f:
                  f.write(updated_content)
              
              # Git operations
              os.chdir('profile-repo')
              subprocess.run(['git', 'config', '--global', 'user.name', 'github-actions[bot]'])
              subprocess.run(['git', 'config', '--global', 'user.email', 'github-actions[bot]@users.noreply.github.com'])
              subprocess.run(['git', 'add', 'README.md'])
              
              # Check if there are changes to commit
              result = subprocess.run(['git', 'diff', '--staged', '--quiet'], capture_output=True)
              if result.returncode == 1:  # Changes detected
                  subprocess.run(['git', 'commit', '-m', 'Update NYT puzzle stats'])
                  subprocess.run(['git', 'push'])
                  print("Changes pushed to profile repository")
                  return True
              else:
                  print("No changes to commit")
                  return False

          if __name__ == "__main__":
              update_profile_readme()
          EOF

          python update_profile.py
